Models/JobPosting.cs
using Microsoft.AspNetCore.Identity;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DevSpot.Models
{
    public class JobPosting
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Title { get; set; }
        [Required]
        public string Description { get; set; }
        [Required]
        public string Company { get; set; }
        [Required]
        public string Location { get; set; }

        public DateTime PostedDate { get; set; } = DateTime.UtcNow;

        public bool IsApproved { get; set; }

        [Required]
        public  string UserId { get; set; }

        [ForeignKey(nameof(UserId))]
        public IdentityUser User { get; set; }

    }
}

ViewModels/JobPostingViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace DevSpot.ViewModels
{
    public class JobPostingViewModel
    {

        [Required]
        public string Title { get; set; }
        [Required]
        public string Description { get; set; }
        [Required]
        public string Company { get; set; }
        [Required]
        public string Location { get; set; }

    }
}

Controllers/JobPostingsController.cs
using DevSpot.Constants;
using DevSpot.Models;
using DevSpot.Repositories;
using DevSpot.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace DevSpot.Controllers
{
    [Authorize]
    public class JobPostingsController : Controller
    {
        private readonly IRepository<JobPosting> _repository;
        private readonly UserManager<IdentityUser> _userManager;

        public JobPostingsController(
            IRepository<JobPosting> repository,
            UserManager<IdentityUser> userManager)
        {
            _repository = repository;
            _userManager = userManager;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var jobPostings = await _repository.GetAllAsync();

            if (User.IsInRole(Roles.Employer))
            {
                var allJobPosting = await _repository.GetAllAsync();
                var userid = _userManager.GetUserId(User);
                var filteredJobPosting = allJobPosting.Where(jp => jp.UserId == userid);
                return View(filteredJobPosting);
            }
            var jobPosting = await _repository.GetAllAsync();

            return View(jobPosting);
        }

        [Authorize(Roles = "Admin, Employer")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(JobPostingViewModel jobPostingVm)
        {
            var jobPosting = new JobPosting
            {
                Title = jobPostingVm.Title,
                Description = jobPostingVm.Description,
                Company = jobPostingVm.Company,
                Location = jobPostingVm.Location,
                UserId = _userManager.GetUserId(User),
            };
            if (ModelState.IsValid)
            {
                await _repository.AddAsync(jobPosting);
                return RedirectToAction(nameof(Index));
            }

            return View(jobPostingVm);
        }

        [HttpDelete]
        [Authorize(Roles = "Admin, Employer")]
        public async Task<IActionResult> Delete(int id)
        {
            var jobPosting = await _repository.GetById(id);
            if (jobPosting == null)
            {
                return NotFound();
            }

            var userId = _userManager.GetUserId(User);
            if (User.IsInRole(Roles.Admin) == false && jobPosting.UserId != userId)
            {
                return Forbid();
            }

            await _repository.DeleteAsync(id);
            return Ok();
        }
    }

}

Views/JobPostings/Create.cshtml
@model DevSpot.ViewModels.JobPostingViewModel;

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div class="d-flex justify-content-center align-items-center" style="min-height: 50vh;">
    <form method="post" action="Create" class="text-center">
        <div class="mb-2 text-start">
            <label asp-for="Title" class="form-label"></label>
            <textarea asp-for="Title" class="form-control"></textarea>
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
        <div class="mb-2 text-start">
            <label asp-for="Description" class="form-label"></label>
            <input type="text" asp-for="Description" class="form-control" />
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>    
        <div class="mb-2 text-start">
            <label asp-for="Company" class="form-label"></label>
            <input type="text" asp-for="Company" class="form-control" />
            <span asp-validation-for="Company" class="text-danger"></span>
        </div>
        <div class="mb-2 text-start">
            <label asp-for="Location" class="form-label"></label>
            <input type="text" asp-for="Location" class="form-control" />
            <span asp-validation-for="Location" class="text-danger"></span>
        </div>
        <div class="d-flex justify-content-center mt-3 gap-3">
            <button type="submit" class="btn btn-primary">Create</button>
            <a href="@Url.Action("Index", "JobPostings")" class="btn btn-secondary">Back</a>
        </div>
        
    </form>
</div>


@section Scripts{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");

    }
}

Views/JobPostings/Index.cshtml
@using DevSpot.Constants;
@model IEnumerable<JobPosting>

<div class="list-group">
    @foreach (var jobPosting in Model)
    {
        <div class="list-group-item" id="job-posting-@jobPosting.Id">
            <h3>@jobPosting.Title</h3>
            <p>@jobPosting.Description</p>
            <p> <strong>Company:</strong>@jobPosting.Company</p>
            <p> <strong>Location:</strong>@jobPosting.Location</p>
            <p> <strong>Posted Date:</strong>@jobPosting.PostedDate.ToShortDateString()</p>

            @if (User.IsInRole(Roles.Admin) || User.IsInRole(Roles.Employer))
            {
                <div>
                    <button onclick="deleteJobPosting(@jobPosting.Id)" class="btn btn-sm btn-danger">Delete</button>
                </div>
            }
        </div>
    }
</div>

@section Scripts {
    <script>
        function deleteJobPosting(id){
            if(confirm("Really want to delete job posting with ID: " + id + "?")){
                $.ajax({
                    url: "@Url.Action("Delete", "JobPostings")/" + id,
                    type: 'DELETE',
                    success: function(result){
                        $("#job-posting-" + id).remove();
                    },
                    error: function (err){
                        alert("An error occurred");
                    }
                });
            }
        }
    </script>
}